apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config
  namespace: myapp
data:
  application.properties: |
    server.port=8080
    spring.datasource.url=jdbc:mysql://db:3306/mydb
    spring.datasource.username=root
    spring.datasource.password=secret
