apiVersion: apps/v1
kind: Deployment
metadata:
  name: meal-track
  namespace: digestive-insights
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meal-track
  template:
    metadata:
      labels:
        app: meal-track
    spec:
      containers:
        - name: meal-track
          image: nexus.ocrespo.com/docker/crm-accounts:1.1.0-20250322.221359
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: meal-track-config
