apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: nexus.example.com/myapp:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: myapp-config
