apiVersion: v1
kind: Service
metadata:
  name: meal-track-service
  namespace: digestive-insights
spec:
  selector:
    app: meal-track
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
